//MULTIPLE PRODUTS
export const GET_DATA_REQUEST="GET_DATA_REQUEST";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_FAILED="GET_DATA_FAILED";


//SINGLE PRODUCT
export const GET_DETAILS_REQUEST="GET_DETAILS_REQUEST";
export const GET_DETAILS_SUCCESS="GET_DETAILS_SUCCESS";
export const GET_DETAILS_FAILED="GET_DETAILS_FAILED";


//Feature Product
export const FEATURE_PRODUCT_REQUEST="FEATURE_PRODUCT_REQUEST";
export const FEATURE_PRODUCT_SUCCESS="FEATURE_PRODUCT_SUCCESS";
export const FEATURE_PRODUCT_FAILED="FEATURE_PRODUCT_FAILED";
